name: ZapScan

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: 'http://demovideo-dev.eba-5etrpdsa.us-east-2.elasticbeanstalk.com'
